LTHOME ?= $(HOME)/logontools
STAMPS=0/stamp.pred-all 1/stamp.pred-all 2/stamp.pred-all

all:	stamp.updated

clean:
	rm -f stamp.updated

stamp.updated:	$(STAMPS)
	touch $@

%/Makefile:	$(LTHOME)/makefiles/Makefile.profile
	cp $< $@

%/stamp.pred-all:	%/Makefile
	make -C $* stamp.pred-all

.PHONY:	clean all
