#!/usr/bin/make

DTHOME		?= $(HOME)/delphintools
PROFILES	:= $(foreach n,$(shell seq -w 6 100),tc-jaen-$(n))
tcdir		:= $(HOME)/research/data/parallel/tanaka/tc-0906/bitext/train/sub
src			:= ja
tgt			:= en

include $(DTHOME)/makefiles/Makefile.root

tc-jaen-%/bitext:	$(tcdir)/tanaka-train-jaen-%.txt
	logon_do -b $< tc-jaen-$*

tc-jaen-%/Makefile:	$(DTHOME)/makefiles/Makefile.treebank tc-jaen-%/bitext Makefile.lang
	cp $< $@

Makefile.lang:	$(DTHOME)/makefiles/Makefile.$(src)$(tgt)
	cp $< $@
